#!/bin/sh
# Sourced from https://github.com/BurntSushi/ripgrep/
# Ripgrep is licensed under the MIT license:
# https://github.com/BurntSushi/ripgrep/blob/master/LICENSE-MIT

if ! command -V sudo; then
  apt-get update
  apt-get install -y --no-install-recommends sudo
fi
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  zsh xz-utils liblz4-tool musl-tools brotli zstd